name = "Literati"
license = "MIT"
licenselink = "https://github.com/pvcodes/literati/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/pvcodes/literati"
tags = []
features = []
min_version = "0.31.1"

[author]
name = "Pranjal Verma"
homepage = "https://pvcodes.in"

[original]
name = ""
homepage = ""
repo = "https://github.com/keichi/literati"

[extensions]
[extensions.passthrough]
enable = true
[extensions.passthrough.delimiters]
[[extensions.passthrough.delimiters.block]]
open = "["
close = "]"
[[extensions.passthrough.delimiters.block]]
open = "$$"
close = "$$"
[[extensions.passthrough.delimiters.inline]]
open = "("
close = ")"
[[extensions.passthrough.delimiters.inline]]
open = "$"
close = "$"


[params]
math = true
